import Head from "next/head";
import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { Button } from "antd";
import Navbar from "@/components/Layout/Navbar";
import HomeCover from "@/components/home/cover";
import ProfessionCard from "@/components/profession";
import ProfessionTest from "@/components/consultant";
import Consultant from "@/components/profession-tests";
import University from "@/components/university";
import useFetch from "./hooks/fetchData";
export default function Home(messages) {
  // const {loading, error, data} = useFetch({ url: "http://localhost:1337/api" });
  // console.log(data, "this is data ==============");
  return (
    <Navbar>
      <Head>
        <title>moli.mn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="2xl:mx-56 lg:mx-36 mt-20 flex flex-col ">
        <HomeCover />
      </div>
      <div className="bg-[#cce6ff]/30 h-screen flex items-center  ">
        <ProfessionCard />
      </div>
      <div className=" h-screen ">
        <Consultant />
      </div>
      <div className="h-screen  mb-20">
        <ProfessionTest />
      </div>
      <div className="h-screen">
        <University />
      </div>
    </Navbar>
  );
}

// export async function getStaticProps() {
//   const client = new ApolloClient({
//     uri: "http://localhost:1337/graphql",
//     cache: new InMemoryCache(),
//   });
//   console.log("cleaint ------->");
//   const { data } = await client.query({
//     query: gql`
//       query {
//         professionCardNames {
//           data {
//             id
//             attributes {
//               cardTitle
//             }
//           }
//         }
//       }
//     `,
//   });
//   console.log(data.professionCardNames, "data----->");
//   return {
//     props: {
//       messages: data.professionCardNames,
//     }, // will be passed to the page component as props
//   };
// }
