import Head from "next/head";
import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { Button } from "antd";
import Navbar from "@/components/Layout/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* <Button>Hello World</Button>
      <h1 className="text-3xl font-bold underline text-slate-500">
        Hello world!
      </h1> */}
    </>
  );
}
