import Head from "next/head";
import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { Button } from "antd";
import Navbar from "@/components/Layout/Navbar";
import HomeCover from "@/components/home/cover";
import ProfessionCard from "@/components/profession";
import ProfessionTest from "@/components/consultant";
import Consultant from "@/components/profession-tests";
import University from "@/components/university";

export default function Home() {
  return (
    <Navbar>
      <Head>
        <title>moli.mn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="2xl:mx-56 lg:mx-36 mt-20 flex flex-col ">
        <HomeCover />
      </div>
      <div className="bg-[#cce6ff]/30 h-screen flex items-center  ">
        <ProfessionCard />
      </div>
      <div className=" h-screen ">
        <Consultant />
      </div>
      <div className="h-screen  ">
        <ProfessionTest />
      </div>
      <div className="h-screen">
        <University />
      </div>
    </Navbar>
  );
}
